#!/bin/sh

echo "/* Automatically generated by generate-hooklist.sh */"

print_hook_list () {
	cat <<EOF
static const char *hook_name_list[] = {
EOF
	grep -C1 -h '^~~~' Documentation/githooks.txt |
	grep '^[a-z0-9][a-z0-9-]*$' |
	sort |
	sed 's/^.*$/	"&",/'
	cat <<EOF
	NULL,
};
EOF
}

echo
print_hook_list
