#!/bin/sh
#
# Usage: ./generate-builtin-list.sh >builtin-list.h

builtin_cmd_list () {
	sed -n \
		-e '/^	{ ".*cmd_/ {
			s/.* \(cmd_[^, ]*\).*/\1/;
			p;
		} ' \
		<git.c
}

builtin_list () {
	printf "int %s(int argc, const char **argv, const char *prefix);\n" $(builtin_cmd_list)
}

cat <<EOF
/* Automatically generated by generate-builtin-list.sh */

$(builtin_list)
EOF
