#!/bin/sh

HT='	'

advice_list () {
	sed -n \
		-e '/^advice.*::$/d' \
		-e "/::/ {
			s/^$HT//;
			s/::\$//;
			p;
		}" \
	    <Documentation/config/advice.txt
}

txt2label () {
	sed \
		-e 's/\([^_]\)\([[:upper:]]\)/\1_\2/g' \
		-e 's/^/ADVICE_/' |
		tr '[:lower:]' '[:upper:]'
}

advice_labels () {
	advice_list |
	txt2label
}

listify () {
	sed \
		-e "2,\$s/^/$HT/" \
		-e 's/$/,/'
}

advice_labels_manual () {
	cat <<-\EOF
	ADVICE_OBJECT_NAME_WARNING
	EOF
}

case "$#" in
1) ;;
*)
	echo "usage: $0 advice-type.h >advice-type.h"
	exit 1
esac

case "$1" in
advice-type.h)
	cat <<EOF
/* Automatically generated by generate-advice.sh */

enum advice_type {
	/* Manually listed, needs adding to Documentation/config/advice.txt */
	$(advice_labels_manual | listify)

	/* Auto-generated from Documentation/config/advice.txt */
	$(advice_labels | listify)
};
EOF
	;;
*)
	echo "$0: unknown target $1" >&2
	exit 1
	;;
esac
