#!/bin/sh

while test $# != 0
do
	case "$1" in
	--X=*)
		X="${1#--X=}"
		;;
	--RM=*)
		RM="${1#--RM=}"
		;;
	--bindir=*)
		bindir="${1#--bindir=}"
		;;
	--bindir-relative=*)
		bindir_relative="${1#--bindir-relative=}"
		;;
	--execdir=*)
		execdir="${1#--execdir=}"
		;;
	--destdir-from-execdir=*)
		destdir_from_execdir="${1#--destdir-from-execdir=}"
		;;
	--flag-install-symlinks=*)
		INSTALL_SYMLINKS="${1#--flag-install-symlinks=}"
		;;
	--flag-no-install-hardlinks=*)
		NO_INSTALL_HARDLINKS="${1#--flag-no-install-hardlinks=}"
		;;
	--flag-no-cross-directory-hardlinks=*)
		NO_CROSS_DIRECTORY_HARDLINKS="${1#--flag-no-cross-directory-hardlinks=}"
		;;
	--flag-no-install-cp-fallback=*)
		NO_INSTALL_CP_FALLBACK="${1#--flag-no-install-cp-fallback=}"
		;;
	--list-bindir-standalone=*)
		list_bindir_standalone="${1#--list-bindir-standalone=}"
		;;
	--list-bindir-git-dashed=*)
		list_bindir_git_dashed="${1#--list-bindir-git-dashed=}"
		;;
	--list-execdir-git-dashed=*)
		list_execdir_git_dashed="${1#--list-execdir-git-dashed=}"
		;;
	--list-execdir-curl-aliases=*)
		list_execdir_curl_aliases="${1#--list-execdir-curl-aliases=}"
		;;

	*)
		echo "Unknown option $1"
		exit 1
		;;
	esac
	shift
done &&

if test "$bindir/" != "$execdir/"
then
	for p in $list_bindir_standalone; do
		$RM "$execdir/$p" &&
		test -n "$INSTALL_SYMLINKS" &&
		ln -s "$destdir_from_execdir/$bindir_relative/$p" "$execdir/$p" ||
		{ test -z "$NO_INSTALL_HARDLINKS$NO_CROSS_DIRECTORY_HARDLINKS" &&
		  ln "$bindir/$p" "$execdir/$p" ||
		  cp "$bindir/$p" "$execdir/$p" || exit; }
	done
fi &&

for p in $list_bindir_git_dashed
do
	$RM "$bindir/$p" &&
	test -n "$INSTALL_SYMLINKS" &&
	ln -s "git$X" "$bindir/$p" ||
	{ test -z "$NO_INSTALL_HARDLINKS" &&
	  ln "$bindir/git$X" "$bindir/$p" ||
	  ln -s "git$X" "$bindir/$p" ||
	  cp "$bindir/git$X" "$bindir/$p" || exit; }
done &&

for p in $list_execdir_git_dashed; do
	$RM "$execdir/$p" &&
	test -n "$INSTALL_SYMLINKS" &&
	ln -s "$destdir_from_execdir/$bindir_relative/git$X" "$execdir/$p" ||
	{ test -z "$NO_INSTALL_HARDLINKS" &&
	  ln "$execdir/git$X" "$execdir/$p" ||
	  ln -s "git$X" "$execdir/$p" ||
	  cp "$execdir/git$X" "$execdir/$p" || exit; }
done &&

for p in $list_execdir_curl_aliases; do
	$RM "$execdir/$p" &&
	test -n "$INSTALL_SYMLINKS" &&
	ln -s "git-remote-http$X" "$execdir/$p" ||
	{ test -z "$NO_INSTALL_HARDLINKS" &&
	  ln "$execdir/git-remote-http$X" "$execdir/$p" ||
	  ln -s "git-remote-http$X" "$execdir/$p" ||
	  cp "$execdir/git-remote-http$X" "$execdir/$p" || exit; }
done
